import type { TransportHub } from './transport.js';

function es(
  slug: string,
  nameEs: string,
  nameAr: string,
  opts?: { popular?: boolean },
): TransportHub {
  return {
    slug,
    zone: 'espana',
    nameEs,
    nameAr,
    country: 'ES',
    flag: '🇪🇸',
    popular: opts?.popular,
  };
}

/** 50 provincias + Ceuta y Melilla */
export const SPAIN_PROVINCE_HUBS: TransportHub[] = [
  es('a-coruna', 'A Coruña', 'لا كورونيا'),
  es('alava', 'Álava', 'ألافا'),
  es('albacete', 'Albacete', 'الباسيت'),
  es('alicante', 'Alicante', 'أليكانتي', { popular: true }),
  es('almeria', 'Almería', 'المرية', { popular: true }),
  es('asturias', 'Asturias', 'أستورياس'),
  es('avila', 'Ávila', 'أفيلا'),
  es('badajoz', 'Badajoz', 'باداخوز'),
  es('baleares', 'Islas Baleares', 'جزر البليار'),
  es('barcelona', 'Barcelona', 'برشلونة', { popular: true }),
  es('burgos', 'Burgos', 'بورغوس'),
  es('caceres', 'Cáceres', 'قصرش'),
  es('cadiz', 'Cádiz', 'قادس'),
  es('cantabria', 'Cantabria', 'كانتابريا'),
  es('castellon', 'Castellón', 'كاستيون'),
  es('ceuta', 'Ceuta', 'سبتة'),
  es('ciudad-real', 'Ciudad Real', 'سيوداد ريال'),
  es('cordoba', 'Córdoba', 'قرطبة'),
  es('cuenca', 'Cuenca', 'كوينكا'),
  es('girona', 'Girona', 'جيرونا'),
  es('granada', 'Granada', 'غرناطة', { popular: true }),
  es('guadalajara', 'Guadalajara', 'غوادالاخارا'),
  es('guipuzcoa', 'Guipúzcoa', 'غيبوثكويا'),
  es('huelva', 'Huelva', 'هويلفا'),
  es('huesca', 'Huesca', 'هويسكا'),
  es('jaen', 'Jaén', 'جيان'),
  es('la-rioja', 'La Rioja', 'لا ريوخا'),
  es('las-palmas', 'Las Palmas', 'لاس بالماس', { popular: true }),
  es('leon', 'León', 'ليون'),
  es('lleida', 'Lleida', 'لاردة'),
  es('lugo', 'Lugo', 'لوغو'),
  es('madrid', 'Madrid', 'مدريد', { popular: true }),
  es('malaga', 'Málaga', 'مالقة', { popular: true }),
  es('melilla', 'Melilla', 'مليلية'),
  es('murcia', 'Murcia', 'مرسية', { popular: true }),
  es('navarra', 'Navarra', 'نافارا'),
  es('ourense', 'Ourense', 'أورينسي'),
  es('palencia', 'Palencia', 'بالنثيا'),
  es('pontevedra', 'Pontevedra', 'بونتيفيدرا'),
  es('salamanca', 'Salamanca', 'سلامنكا'),
  es('santa-cruz-tenerife', 'Santa Cruz de Tenerife', 'سانتا كروز دي تينيريفه', { popular: true }),
  es('segovia', 'Segovia', 'سيغوفيا'),
  es('sevilla', 'Sevilla', 'إشبيلية', { popular: true }),
  es('soria', 'Soria', 'سوريا'),
  es('tarragona', 'Tarragona', 'طراغونا'),
  es('teruel', 'Teruel', 'تيرويل'),
  es('toledo', 'Toledo', 'طليطلة'),
  es('valencia', 'Valencia', 'فالنسيا', { popular: true }),
  es('valladolid', 'Valladolid', 'بلد الوليد'),
  es('vizcaya', 'Vizcaya / Bilbao', 'بيسكاي', { popular: true }),
  es('zamora', 'Zamora', 'زامورا'),
  es('zaragoza', 'Zaragoza', 'سرقسطة', { popular: true }),
];
