import type { TransportHub } from './transport.js';

/** 58 wilayas de Argelia — prefijo dz- para evitar colisiones de slug */
function dz(
  slug: string,
  nameEs: string,
  nameAr: string,
  opts?: { popular?: boolean },
): TransportHub {
  return {
    slug: `dz-${slug}`,
    zone: 'argelia',
    nameEs,
    nameAr,
    country: 'DZ',
    flag: '',
    popular: opts?.popular,
  };
}

/** Tindouf (wilaya 37) vive en zona `tindouf`; el resto aquí */
export const ALGERIA_WILAYA_HUBS: TransportHub[] = [
  dz('adrar', 'Adrar', 'أدرار'),
  dz('chlef', 'Chlef', 'الشلف', { popular: true }),
  dz('laghouat', 'Laghouat', 'الأغواط'),
  dz('oum-el-bouaghi', 'Oum El Bouaghi', 'أم البواقي'),
  dz('batna', 'Batna', 'باتنة', { popular: true }),
  dz('bejaia', 'Béjaïa', 'بجاية'),
  dz('biskra', 'Biskra', 'بسكرة'),
  dz('bechar', 'Béchar', 'بشار'),
  dz('blida', 'Blida', 'البليدة', { popular: true }),
  dz('bouira', 'Bouira', 'البويرة'),
  dz('tamanrasset', 'Tamanrasset', 'تمنراست'),
  dz('tebessa', 'Tébessa', 'تبسة'),
  dz('tlemcen', 'Tlemcen', 'تلمسان', { popular: true }),
  dz('tiaret', 'Tiaret', 'تيارت'),
  dz('tizi-ouzou', 'Tizi Ouzou', 'تيزي وزو'),
  dz('alger', 'Argel / Alger', 'الجزائر', { popular: true }),
  dz('djelfa', 'Djelfa', 'الجلفة'),
  dz('jijel', 'Jijel', 'جيجل'),
  dz('setif', 'Sétif', 'سطيف', { popular: true }),
  dz('saida', 'Saïda', 'سعيدة'),
  dz('skikda', 'Skikda', 'سكيكدة'),
  dz('sidi-bel-abbes', 'Sidi Bel Abbès', 'سيدي بلعباس', { popular: true }),
  dz('annaba', 'Annaba', 'عنابة', { popular: true }),
  dz('guelma', 'Guelma', 'قالمة'),
  dz('constantine', 'Constantina', 'قسنطينة', { popular: true }),
  dz('medea', 'Médéa', 'المدية'),
  dz('mostaganem', 'Mostaganem', 'مستغانم'),
  dz('msila', "M'Sila", 'مسيلة'),
  dz('mascara', 'Mascara', 'معسكر'),
  dz('ouargla', 'Ouargla', 'ورقلة'),
  dz('oran', 'Orán / Oran', 'وهران', { popular: true }),
  dz('el-bayadh', 'El Bayadh', 'البيض'),
  dz('illizi', 'Illizi', 'إليزي'),
  dz('bordj-bou-arreridj', 'Bordj Bou Arréridj', 'برج بوعريريج'),
  dz('boumerdes', 'Boumerdès', 'بومرداس'),
  dz('el-tarf', 'El Tarf', 'الطارف'),
  dz('tissemsilt', 'Tissemsilt', 'تيسمسيلت'),
  dz('el-oued', 'El Oued', 'الوادي'),
  dz('khenchela', 'Khenchela', 'خنشلة'),
  dz('souk-ahras', 'Souk Ahras', 'سوق أهراس'),
  dz('tipaza', 'Tipaza', 'تيبازة'),
  dz('mila', 'Mila', 'ميلة'),
  dz('ain-defla', 'Aïn Defla', 'عين الدفلى'),
  dz('naama', 'Naâma', 'النعامة'),
  dz('ain-temouchent', 'Aïn Témouchent', 'عين تموشنت'),
  dz('ghardaia', 'Ghardaïa', 'غرداية'),
  dz('relizane', 'Relizane', 'غليزان'),
  dz('timimoun', 'Timimoun', 'تيميمون'),
  dz('bordj-badji-mokhtar', 'Bordj Badji Mokhtar', 'برج باجي مختار'),
  dz('ouled-djellal', 'Ouled Djellal', 'أولاد جلال'),
  dz('beni-abbes', 'Béni Abbès', 'بني عباس'),
  dz('in-salah', 'In Salah', 'عين صالح'),
  dz('in-guezzam', 'In Guezzam', 'عين قزام'),
  dz('touggourt', 'Touggourt', 'تقرت'),
  dz('djanet', 'Djanet', 'جانت'),
  dz('el-mghair', "El M'Ghair", 'المغير'),
  dz('el-meniaa', 'El Meniaa', 'المنيعة'),
];
