import type { TransportHub } from './transport.js';

function fr(
  slug: string,
  nameEs: string,
  nameAr: string,
  opts?: { popular?: boolean },
): TransportHub {
  return {
    slug,
    zone: 'francia',
    nameEs,
    nameAr,
    country: 'FR',
    flag: '🇫🇷',
    popular: opts?.popular,
  };
}

/** 101 departamentos metropolitanos de Francia */
export const FRANCE_DEPARTMENT_HUBS: TransportHub[] = [
  fr('fr-01-ain', 'Ain (01)', 'أين'),
  fr('fr-02-aisne', 'Aisne (02)', 'أيسن'),
  fr('fr-03-allier', 'Allier (03)', 'ألييه'),
  fr('fr-04-alpes-haute-provence', 'Alpes-de-Haute-Provence (04)', 'الألب العليا بروفانس'),
  fr('fr-05-hautes-alpes', 'Hautes-Alpes (05)', 'الألب العليا'),
  fr('fr-06-alpes-maritimes', 'Alpes-Maritimes (06)', 'الألب البحرية', { popular: true }),
  fr('fr-07-ardeche', 'Ardèche (07)', 'أرديش'),
  fr('fr-08-ardennes', 'Ardennes (08)', 'أردين'),
  fr('fr-09-ariege', 'Ariège (09)', 'أرييج'),
  fr('fr-10-aube', 'Aube (10)', 'أوب'),
  fr('fr-11-aude', 'Aude (11)', 'أود'),
  fr('fr-12-aveyron', 'Aveyron (12)', 'أفيرون'),
  fr('fr-13-bouches-du-rhone', 'Bouches-du-Rhône (13)', 'بوش دو رون', { popular: true }),
  fr('fr-14-calvados', 'Calvados (14)', 'كالفادوس'),
  fr('fr-15-cantal', 'Cantal (15)', 'كانتال'),
  fr('fr-16-charente', 'Charente (16)', 'شارنت'),
  fr('fr-17-charente-maritime', 'Charente-Maritime (17)', 'شارنت البحرية'),
  fr('fr-18-cher', 'Cher (18)', 'شير'),
  fr('fr-19-correze', 'Corrèze (19)', 'كوريز'),
  fr('fr-21-cote-dor', "Côte-d'Or (21)", 'كوت دور'),
  fr('fr-22-cotes-darmor', "Côtes-d'Armor (22)", 'كوت دارمور'),
  fr('fr-23-creuse', 'Creuse (23)', 'كروز'),
  fr('fr-24-dordogne', 'Dordogne (24)', 'دوردوني'),
  fr('fr-25-doubs', 'Doubs (25)', 'دوب'),
  fr('fr-26-drome', 'Drôme (26)', 'دروم'),
  fr('fr-27-eure', 'Eure (27)', 'أور'),
  fr('fr-28-eure-et-loir', 'Eure-et-Loir (28)', 'أور ولوار'),
  fr('fr-29-finistere', 'Finistère (29)', 'فينيستير'),
  fr('fr-30-gard', 'Gard (30)', 'غارد'),
  fr('fr-31-haute-garonne', 'Haute-Garonne (31)', 'غارون العليا', { popular: true }),
  fr('fr-32-gers', 'Gers (32)', 'جير'),
  fr('fr-33-gironde', 'Gironde (33)', 'جيروند', { popular: true }),
  fr('fr-34-herault', 'Hérault (34)', 'إيرو'),
  fr('fr-35-ille-et-vilaine', 'Ille-et-Vilaine (35)', 'إيل وفيلان'),
  fr('fr-36-indre', 'Indre (36)', 'أندر'),
  fr('fr-37-indre-et-loire', 'Indre-et-Loire (37)', 'أندر ولوار'),
  fr('fr-38-isere', 'Isère (38)', 'إيزير'),
  fr('fr-39-jura', 'Jura (39)', 'جورا'),
  fr('fr-40-landes', 'Landes (40)', 'لاند'),
  fr('fr-41-loir-et-cher', 'Loir-et-Cher (41)', 'لوار وشير'),
  fr('fr-42-loire', 'Loire (42)', 'لوار'),
  fr('fr-43-haute-loire', 'Haute-Loire (43)', 'لوار العليا'),
  fr('fr-44-loire-atlantique', 'Loire-Atlantique (44)', 'لوار الأطلسية', { popular: true }),
  fr('fr-45-loiret', 'Loiret (45)', 'لوريه'),
  fr('fr-46-lot', 'Lot (46)', 'لوت'),
  fr('fr-47-lot-et-garonne', 'Lot-et-Garonne (47)', 'لوت وغارون'),
  fr('fr-48-lozere', 'Lozère (48)', 'لوزير'),
  fr('fr-49-maine-et-loire', 'Maine-et-Loire (49)', 'ماين ولوار'),
  fr('fr-50-manche', 'Manche (50)', 'مانش'),
  fr('fr-51-marne', 'Marne (51)', 'مارن'),
  fr('fr-52-haute-marne', 'Haute-Marne (52)', 'مارن العليا'),
  fr('fr-53-mayenne', 'Mayenne (53)', 'مايين'),
  fr('fr-54-meurthe-et-moselle', 'Meurthe-et-Moselle (54)', 'مورت وموزيل'),
  fr('fr-55-meuse', 'Meuse (55)', 'موز'),
  fr('fr-56-morbihan', 'Morbihan (56)', 'موربيهان'),
  fr('fr-57-moselle', 'Moselle (57)', 'موزيل'),
  fr('fr-58-nievre', 'Nièvre (58)', 'نيفر'),
  fr('fr-59-nord', 'Nord (59)', 'نور', { popular: true }),
  fr('fr-60-oise', 'Oise (60)', 'واز'),
  fr('fr-61-orne', 'Orne (61)', 'أورن'),
  fr('fr-62-pas-de-calais', 'Pas-de-Calais (62)', 'باد كاليه'),
  fr('fr-63-puy-de-dome', 'Puy-de-Dôme (63)', 'بوي دوم'),
  fr('fr-64-pyrenees-atlantiques', 'Pyrénées-Atlantiques (64)', 'بيرينيه الأطلسية'),
  fr('fr-65-hautes-pyrenees', 'Hautes-Pyrénées (65)', 'بيرينيه العليا'),
  fr('fr-66-pyrenees-orientales', 'Pyrénées-Orientales (66)', 'بيرينيه الشرقية'),
  fr('fr-67-bas-rhin', 'Bas-Rhin (67)', 'الراين الأسفل', { popular: true }),
  fr('fr-68-haut-rhin', 'Haut-Rhin (68)', 'الراين الأعلى'),
  fr('fr-69-rhone', 'Rhône (69)', 'رون', { popular: true }),
  fr('fr-70-haute-saone', 'Haute-Saône (70)', 'سون العليا'),
  fr('fr-71-saone-et-loire', 'Saône-et-Loire (71)', 'سون ولوار'),
  fr('fr-72-sarthe', 'Sarthe (72)', 'سارت'),
  fr('fr-73-savoie', 'Savoie (73)', 'سافوا'),
  fr('fr-74-haute-savoie', 'Haute-Savoie (74)', 'سافوا العليا'),
  fr('fr-75-paris', 'Paris (75)', 'باريس', { popular: true }),
  fr('fr-76-seine-maritime', 'Seine-Maritime (76)', 'السين البحرية'),
  fr('fr-77-seine-et-marne', 'Seine-et-Marne (77)', 'السين ومارن'),
  fr('fr-78-yvelines', 'Yvelines (78)', 'إيفلين'),
  fr('fr-79-deux-sevres', 'Deux-Sèvres (79)', 'دوسيفر'),
  fr('fr-80-somme', 'Somme (80)', 'السوم'),
  fr('fr-81-tarn', 'Tarn (81)', 'تارن'),
  fr('fr-82-tarn-et-garonne', 'Tarn-et-Garonne (82)', 'تارن وغارون'),
  fr('fr-83-var', 'Var (83)', 'فار'),
  fr('fr-84-vaucluse', 'Vaucluse (84)', 'فوكلوز'),
  fr('fr-85-vendee', 'Vendée (85)', 'فونديه'),
  fr('fr-86-vienne', 'Vienne (86)', 'فيين'),
  fr('fr-87-haute-vienne', 'Haute-Vienne (87)', 'فيين العليا'),
  fr('fr-88-vosges', 'Vosges (88)', 'فوج'),
  fr('fr-89-yonne', 'Yonne (89)', 'يون'),
  fr('fr-90-territoire-de-belfort', 'Territoire de Belfort (90)', 'إقليم بلفور'),
  fr('fr-91-essonne', 'Essonne (91)', 'إسون'),
  fr('fr-92-hauts-de-seine', 'Hauts-de-Seine (92)', 'سين العليا'),
  fr('fr-93-seine-saint-denis', 'Seine-Saint-Denis (93)', 'سين سان دوني'),
  fr('fr-94-val-de-marne', 'Val-de-Marne (94)', 'فال دو مارن'),
  fr('fr-95-val-doise', "Val-d'Oise (95)", 'فال دواز'),
  fr('fr-2a-corse-du-sud', 'Corse-du-Sud (2A)', 'كورس الجنوبية'),
  fr('fr-2b-haute-corse', 'Haute-Corse (2B)', 'كورس العليا'),
  // DOM — ultramar
  fr('fr-971-guadeloupe', 'Guadeloupe (971)', 'غوادلوب'),
  fr('fr-972-martinique', 'Martinique (972)', 'مارتينيك'),
  fr('fr-973-guyane', 'Guyane française (973)', 'غيانا الفرنسية'),
  fr('fr-974-la-reunion', 'La Réunion (974)', 'لا ريونيون', { popular: true }),
  fr('fr-976-mayotte', 'Mayotte (976)', 'مايوت'),
];

/** Alias cortos (compatibilidad con rutas y datos existentes) */
export const FRANCE_HUB_ALIASES: TransportHub[] = [
  fr('paris', 'París / Île-de-France', 'باريس', { popular: true }),
  fr('lyon', 'Lyon / Rhône', 'ليون', { popular: true }),
  fr('marseille', 'Marsella / Bouches-du-Rhône', 'مرسيليا', { popular: true }),
  fr('toulouse', 'Toulouse / Haute-Garonne', 'تولوز', { popular: true }),
  fr('bordeaux', 'Burdeos / Gironde', 'بوردو', { popular: true }),
  fr('nantes', 'Nantes / Loire-Atlantique', 'نانت', { popular: true }),
  fr('strasbourg', 'Estrasburgo / Bas-Rhin', 'ستراسبورغ', { popular: true }),
  fr('lille', 'Lille / Nord', 'ليل', { popular: true }),
];
